### PR TITLE
Adding profile filter to the Manage Systems page

### PR DESCRIPTION
**Pull request by vipseixas**
When there are many systems in the table (I have 23 and growing) it is hard do find a specific system, so I copied the profile filter funcionality from the SSH page.

### CODE REVIEW

**Comment by colandre** [comment]
Hello @vipseixas, what about to use CTRL+F ?

**Comment by vipseixas** [comment]
Ctrl-F is a workaround, sure, but it seems to me that a filter has better functionality and also is better for maintaining consistence between the Manage and Admin pages. They are very similar, I don't see why one can have a filter and the other can't.

**Comment by vipseixas** [comment]
There is another benefit with the filter: I can easily check which systems are part of a profile. Now I have to go to the profile and roll over the list of all systems and see which has a marked checkbox.

**Comment by colandre** [comment]
I agree about the application consistency.

Regarding finding systems in a profile I opened an issue #204 allowing the system table sorting by first column (the tick). I don't know if it can help.

**Comment by vipseixas** [comment]
Sorting by the tick would help a lot.

**Comment by skavanagh** [comment]
Thanks @vipseixas

**Comment by skavanagh** [comment]
@colandre I'm good with doing something about https://github.com/skavanagh/KeyBox/issues/204 too.  Just haven't gotten to it yet

**Pull request merged**
